const yup = require('./configuracao');

const schemaAtualizarEmpresa = yup.object().shape({
cnpj: yup.string().max(14),
identificador_matriz_filial: yup.number(),
descricao_matriz_filial: yup.string(),
razao_social: yup.string().max(100),
nome_fantasia: yup.string().max(100),
situacao_cadastral: yup.number(),
descricao_situacao_cadastral: yup.string().max(150),
data_situacao_cadastral: yup.string(),
motivo_situacao_cadastral: yup.number(),
nome_cidade_exterior: yup.string().max(80).nullable(),
codigo_natureza_juridica: yup.number(),
data_inicio_atividade: yup.string(),
cnae_fiscal: yup.number(),
cnae_fiscal_descricao: yup.string(),
descricao_tipo_logradouro: yup.string().max(40),
logradouro: yup.string().max(100),
numero: yup.string().max(10),
complemento: yup.string().max(100),
bairro: yup.string().max(50),
cep: yup.number(),
uf: yup.string().max(2),
codigo_municipio: yup.number(),
municipio: yup.string().max(50),
ddd_telefone_1: yup.string().max(15),
ddd_telefone_2: yup.string().max(15).nullable(),
ddd_fax: yup.string().max(15).nullable(),
qualificacao_do_responsavel: yup.number(),
capital_social: yup.number(),
porte: yup.number(),
descricao_porte: yup.string().max(30),
opcao_pelo_simples: yup.boolean(),
data_opcao_pelo_simples: yup.string().nullable(),
data_exclusao_do_simples: yup.string().nullable(),
opcao_pelo_mei: yup.boolean(),
situacao_especial: yup.string().nullable(),
data_situacao_especial: yup.string().nullable(),
});

module.exports = schemaAtualizarEmpresa;